"""The 66-book canon, with the abbreviations people actually type.

Kept as plain data rather than a parser dependency: the canon does not change,
and owning the alias list means a reference that fails to resolve is fixed by
adding one string here.
"""

# (canonical name, OSIS code, aliases)
# Aliases are matched after normalization (lowercased, periods dropped, leading
# roman numerals and ordinals folded to digits), so "1 Cor.", "I Corinthians"
# and "1cor" all arrive here as "1 cor".
CANON = [
    ("Genesis", "Gen", ["gen", "ge", "gn"]),
    ("Exodus", "Exod", ["exod", "exo", "ex"]),
    ("Leviticus", "Lev", ["lev", "le", "lv"]),
    ("Numbers", "Num", ["num", "nu", "nm", "nb"]),
    ("Deuteronomy", "Deut", ["deut", "de", "dt"]),
    ("Joshua", "Josh", ["josh", "jos", "jsh"]),
    ("Judges", "Judg", ["judg", "jdg", "jdgs", "jg"]),
    ("Ruth", "Ruth", ["ruth", "rth", "ru"]),
    ("1 Samuel", "1Sam", ["1 sam", "1 sa", "1 sm", "1 s"]),
    ("2 Samuel", "2Sam", ["2 sam", "2 sa", "2 sm", "2 s"]),
    ("1 Kings", "1Kgs", ["1 kgs", "1 kin", "1 ki", "1 k"]),
    ("2 Kings", "2Kgs", ["2 kgs", "2 kin", "2 ki", "2 k"]),
    ("1 Chronicles", "1Chr", ["1 chron", "1 chr", "1 ch"]),
    ("2 Chronicles", "2Chr", ["2 chron", "2 chr", "2 ch"]),
    ("Ezra", "Ezra", ["ezra", "ezr"]),
    ("Nehemiah", "Neh", ["neh", "ne"]),
    ("Esther", "Esth", ["esth", "est", "es"]),
    ("Job", "Job", ["job", "jb"]),
    ("Psalms", "Ps", ["psalms", "psalm", "pslm", "psa", "psm", "ps"]),
    ("Proverbs", "Prov", ["prov", "prv", "pro", "pr"]),
    ("Ecclesiastes", "Eccl", ["ecclesiastes", "eccl", "ecc", "ec", "qoheleth", "qoh"]),
    ("Song of Songs", "Song", ["song of songs", "song of solomon", "canticles", "song", "sos", "cant"]),
    ("Isaiah", "Isa", ["isa", "is"]),
    ("Jeremiah", "Jer", ["jer", "je", "jr"]),
    ("Lamentations", "Lam", ["lam", "la"]),
    ("Ezekiel", "Ezek", ["ezek", "eze", "ezk"]),
    ("Daniel", "Dan", ["dan", "da", "dn"]),
    ("Hosea", "Hos", ["hos", "ho"]),
    ("Joel", "Joel", ["joel", "jol", "jl"]),
    ("Amos", "Amos", ["amos", "am"]),
    ("Obadiah", "Obad", ["obad", "oba", "ob"]),
    ("Jonah", "Jonah", ["jonah", "jnh", "jon"]),
    ("Micah", "Mic", ["mic", "mc"]),
    ("Nahum", "Nah", ["nah", "na"]),
    ("Habakkuk", "Hab", ["hab", "hb"]),
    ("Zephaniah", "Zeph", ["zeph", "zep", "zp"]),
    ("Haggai", "Hag", ["hag", "hg"]),
    ("Zechariah", "Zech", ["zech", "zec", "zch"]),
    ("Malachi", "Mal", ["mal", "ml"]),
    ("Matthew", "Matt", ["matt", "mat", "mt"]),
    ("Mark", "Mark", ["mark", "mrk", "mk", "mr"]),
    ("Luke", "Luke", ["luke", "luk", "lk"]),
    ("John", "John", ["john", "jhn", "jn"]),
    ("Acts", "Acts", ["acts", "act", "ac"]),
    ("Romans", "Rom", ["rom", "ro", "rm"]),
    ("1 Corinthians", "1Cor", ["1 corinthians", "1 cor", "1 co"]),
    ("2 Corinthians", "2Cor", ["2 corinthians", "2 cor", "2 co"]),
    ("Galatians", "Gal", ["gal", "ga"]),
    ("Ephesians", "Eph", ["ephes", "eph"]),
    ("Philippians", "Phil", ["philippians", "phil", "php", "pp"]),
    ("Colossians", "Col", ["col", "co"]),
    ("1 Thessalonians", "1Thess", ["1 thessalonians", "1 thess", "1 thes", "1 th"]),
    ("2 Thessalonians", "2Thess", ["2 thessalonians", "2 thess", "2 thes", "2 th"]),
    ("1 Timothy", "1Tim", ["1 timothy", "1 tim", "1 ti"]),
    ("2 Timothy", "2Tim", ["2 timothy", "2 tim", "2 ti"]),
    ("Titus", "Titus", ["titus", "tit", "ti"]),
    ("Philemon", "Phlm", ["philemon", "philem", "phlm", "phm", "pm"]),
    ("Hebrews", "Heb", ["hebr", "heb"]),
    ("James", "Jas", ["jas", "jam", "jm"]),
    ("1 Peter", "1Pet", ["1 peter", "1 pet", "1 pe", "1 pt", "1 p"]),
    ("2 Peter", "2Pet", ["2 peter", "2 pet", "2 pe", "2 pt", "2 p"]),
    ("1 John", "1John", ["1 john", "1 jhn", "1 jn", "1 j"]),
    ("2 John", "2John", ["2 john", "2 jhn", "2 jn", "2 j"]),
    ("3 John", "3John", ["3 john", "3 jhn", "3 jn", "3 j"]),
    ("Jude", "Jude", ["jude", "jud", "jd"]),
    ("Revelation", "Rev", ["revelations", "revelation", "rev", "re"]),
]
